/**
 * Canonical language ids → Piston API + file defaults
 * Piston: https://emkc.org/api/v2/piston/runtimes
 */

export type PistonSpec = {
  language: string;
  version: string;
  filename: string;
  /** Run via Live Preview instead of Piston */
  preview?: boolean;
};

/** Map IDE lang id → Piston */
export const PISTON_MAP: Record<string, PistonSpec> = {
  // Web
  html: { language: 'html', version: '*', filename: 'index.html', preview: true },
  css: { language: 'html', version: '*', filename: 'styles.css', preview: true },
  javascript: { language: 'javascript', version: '*', filename: 'main.js' },
  typescript: { language: 'typescript', version: '*', filename: 'main.ts' },
  nodejs: { language: 'javascript', version: '*', filename: 'main.js' },
  react: { language: 'javascript', version: '*', filename: 'App.jsx', preview: true },
  vue: { language: 'javascript', version: '*', filename: 'App.vue', preview: true },
  angular: { language: 'typescript', version: '*', filename: 'app.component.ts', preview: true },
  svelte: { language: 'javascript', version: '*', filename: 'App.svelte', preview: true },
  jquery: { language: 'javascript', version: '*', filename: 'main.js', preview: true },
  htmx: { language: 'html', version: '*', filename: 'index.html', preview: true },
  threejs: { language: 'javascript', version: '*', filename: 'main.js', preview: true },
  d3: { language: 'javascript', version: '*', filename: 'main.js', preview: true },
  chartjs: { language: 'javascript', version: '*', filename: 'main.js', preview: true },
  tailwind: { language: 'html', version: '*', filename: 'index.html', preview: true },
  bootstrap: { language: 'html', version: '*', filename: 'index.html', preview: true },
  deno: { language: 'typescript', version: '*', filename: 'main.ts' },
  bun: { language: 'javascript', version: '*', filename: 'main.js' },
  mui: { language: 'javascript', version: '*', filename: 'App.jsx', preview: true },
  chakra: { language: 'javascript', version: '*', filename: 'App.jsx', preview: true },
  shadcn: { language: 'javascript', version: '*', filename: 'App.tsx', preview: true },
  alpine: { language: 'html', version: '*', filename: 'index.html', preview: true },
  leaflet: { language: 'html', version: '*', filename: 'index.html', preview: true },
  phaser: { language: 'javascript', version: '*', filename: 'game.js', preview: true },
  echarts: { language: 'html', version: '*', filename: 'index.html', preview: true },
  mermaid: { language: 'html', version: '*', filename: 'index.html', preview: true },
  plsql: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  mariadb: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  oracle: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  mssql: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  cassandra: { language: 'javascript', version: '*', filename: 'query.js' },
  duckdb: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  clickhouse: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  brainfuck: { language: 'brainfuck', version: '*', filename: 'main.bf' },
  octave: { language: 'octave', version: '*', filename: 'main.m' },
  cobol: { language: 'cobol', version: '*', filename: 'main.cob' },
  prolog: { language: 'prolog', version: '*', filename: 'main.pl' },
  scheme: { language: 'scheme', version: '*', filename: 'main.scm' },
  racket: { language: 'racket', version: '*', filename: 'main.rkt' },
  ocaml: { language: 'ocaml', version: '*', filename: 'main.ml' },
  verilog: { language: 'verilog', version: '*', filename: 'main.v' },
  awk: { language: 'bash', version: '*', filename: 'main.awk' },
  python2: { language: 'python2', version: '*', filename: 'main.py' },

  coffeescript: { language: 'coffeescript', version: '*', filename: 'main.coffee' },

  // Systems / general
  python: { language: 'python', version: '*', filename: 'main.py' },
  java: { language: 'java', version: '*', filename: 'Main.java' },
  c: { language: 'c', version: '*', filename: 'main.c' },
  cpp: { language: 'c++', version: '*', filename: 'main.cpp' },
  'c++': { language: 'c++', version: '*', filename: 'main.cpp' },
  csharp: { language: 'csharp', version: '*', filename: 'Program.cs' },
  go: { language: 'go', version: '*', filename: 'main.go' },
  rust: { language: 'rust', version: '*', filename: 'main.rs' },
  php: { language: 'php', version: '*', filename: 'main.php' },
  ruby: { language: 'ruby', version: '*', filename: 'main.rb' },
  kotlin: { language: 'kotlin', version: '*', filename: 'Main.kt' },
  swift: { language: 'swift', version: '*', filename: 'main.swift' },
  lua: { language: 'lua', version: '*', filename: 'main.lua' },
  sql: { language: 'sqlite3', version: '*', filename: 'main.sql' },
  mysql: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  postgresql: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  sqlite: { language: 'sqlite3', version: '*', filename: 'query.sql' },
  mongodb: { language: 'javascript', version: '*', filename: 'query.js' },
  redis: { language: 'bash', version: '*', filename: 'commands.sh' },

  bash: { language: 'bash', version: '*', filename: 'main.sh' },
  shell: { language: 'bash', version: '*', filename: 'main.sh' },
  powershell: { language: 'powershell', version: '*', filename: 'main.ps1' },
  assembly: { language: 'assembly', version: '*', filename: 'main.asm' },
  nasm: { language: 'nasm', version: '*', filename: 'main.asm' },
  perl: { language: 'perl', version: '*', filename: 'main.pl' },
  r: { language: 'r', version: '*', filename: 'main.r' },
  dart: { language: 'dart', version: '*', filename: 'main.dart' },
  scala: { language: 'scala', version: '*', filename: 'Main.scala' },
  groovy: { language: 'groovy', version: '*', filename: 'main.groovy' },
  haskell: { language: 'haskell', version: '*', filename: 'main.hs' },
  elixir: { language: 'elixir', version: '*', filename: 'main.exs' },
  erlang: { language: 'erlang', version: '*', filename: 'main.erl' },
  clojure: { language: 'clojure', version: '*', filename: 'main.clj' },
  fsharp: { language: 'fsharp', version: '*', filename: 'main.fs' },
  fortran: { language: 'fortran', version: '*', filename: 'main.f90' },
  pascal: { language: 'pascal', version: '*', filename: 'main.pas' },
  vb: { language: 'basic.net', version: '*', filename: 'Program.vb' },
  'objective-c': { language: 'objective-c', version: '*', filename: 'main.m' },
  julia: { language: 'julia', version: '*', filename: 'main.jl' },
  zig: { language: 'zig', version: '*', filename: 'main.zig' },
  nim: { language: 'nim', version: '*', filename: 'main.nim' },
  crystal: { language: 'crystal', version: '*', filename: 'main.cr' },
  cobol: { language: 'cobol', version: '*', filename: 'main.cob' },
  lisp: { language: 'lisp', version: '*', filename: 'main.lisp' },
  prolog: { language: 'prolog', version: '*', filename: 'main.pl' },
  ocaml: { language: 'ocaml', version: '*', filename: 'main.ml' },
  vlang: { language: 'vlang', version: '*', filename: 'main.v' },
  solidity: { language: 'solidity', version: '*', filename: 'main.sol' },
  plaintext: { language: 'bash', version: '*', filename: 'main.txt' },
};

/** Extension → IDE lang id */
export const EXT_TO_LANG: Record<string, string> = {
  html: 'html',
  htm: 'html',
  css: 'css',
  scss: 'css',
  less: 'css',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'react',
  ts: 'typescript',
  tsx: 'typescript',
  py: 'python',
  pyw: 'python',
  java: 'java',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  go: 'go',
  rs: 'rust',
  php: 'php',
  rb: 'ruby',
  kt: 'kotlin',
  kts: 'kotlin',
  swift: 'swift',
  lua: 'lua',
  sql: 'sql',
  sh: 'bash',
  bash: 'bash',
  zsh: 'shell',
  ps1: 'powershell',
  pl: 'perl',
  r: 'r',
  dart: 'dart',
  scala: 'scala',
  groovy: 'groovy',
  hs: 'haskell',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  clj: 'clojure',
  fs: 'fsharp',
  f90: 'fortran',
  f: 'fortran',
  pas: 'pascal',
  vb: 'vb',
  m: 'objective-c',
  jl: 'julia',
  zig: 'zig',
  nim: 'nim',
  cr: 'crystal',
  coffee: 'coffeescript',
  vue: 'vue',
  svelte: 'svelte',
  asm: 'assembly',
  s: 'assembly',
  cob: 'cobol',
  lisp: 'lisp',
  ml: 'ocaml',
  v: 'vlang',
  sol: 'solidity',
  txt: 'plaintext',
  md: 'plaintext',
};

/** Normalize monaco / node language string → IDE id */
export function normalizeLangId(raw?: string | null): string | null {
  if (!raw) return null;
  const l = raw.toLowerCase().trim();
  const aliases: Record<string, string> = {
    js: 'javascript',
    ts: 'typescript',
    'c++': 'cpp',
    cplusplus: 'cpp',
    'c#': 'csharp',
    cs: 'csharp',
    py: 'python',
    rb: 'ruby',
    sh: 'bash',
    shellscript: 'bash',
    zsh: 'shell',
    'objective-c': 'objective-c',
    objc: 'objective-c',
    'f#': 'fsharp',
    'fsharp': 'fsharp',
    basic: 'vb',
    'vb.net': 'vb',
    sqlite: 'sqlite',
    sqlite3: 'sql',
    text: 'plaintext',
    txt: 'plaintext',
    markdown: 'plaintext',
    node: 'nodejs',
    'node.js': 'nodejs',
  };
  if (aliases[l]) return aliases[l];
  if (PISTON_MAP[l]) return l;
  return l;
}

/**
 * Detect language for a file.
 * Priority: explicit node.language → extension → null
 * (Never maps css → html for the language id; preview layer handles that.)
 */
export function detectLangFromFile(name: string, nodeLang?: string): string | null {
  const fromNode = normalizeLangId(nodeLang);
  if (fromNode && fromNode !== 'plaintext') return fromNode;

  const lower = (name || '').toLowerCase();
  const ext = lower.includes('.') ? lower.split('.').pop() || '' : '';
  if (ext && EXT_TO_LANG[ext]) return EXT_TO_LANG[ext];

  return fromNode;
}

export const RUN_LANGUAGE_OPTIONS: { id: string; label: string }[] = [
  { id: 'html', label: 'HTML' },
  { id: 'css', label: 'CSS' },
  { id: 'javascript', label: 'JavaScript' },
  { id: 'typescript', label: 'TypeScript' },
  { id: 'nodejs', label: 'Node.js' },
  { id: 'python', label: 'Python' },
  { id: 'java', label: 'Java' },
  { id: 'c', label: 'C' },
  { id: 'cpp', label: 'C++' },
  { id: 'csharp', label: 'C#' },
  { id: 'go', label: 'Go' },
  { id: 'rust', label: 'Rust' },
  { id: 'php', label: 'PHP' },
  { id: 'ruby', label: 'Ruby' },
  { id: 'kotlin', label: 'Kotlin' },
  { id: 'swift', label: 'Swift' },
  { id: 'lua', label: 'Lua' },
  { id: 'sql', label: 'SQL / SQLite' },
  { id: 'bash', label: 'Bash' },
  { id: 'shell', label: 'Shell' },
  { id: 'powershell', label: 'PowerShell' },
  { id: 'perl', label: 'Perl' },
  { id: 'r', label: 'R' },
  { id: 'dart', label: 'Dart' },
  { id: 'scala', label: 'Scala' },
  { id: 'groovy', label: 'Groovy' },
  { id: 'haskell', label: 'Haskell' },
  { id: 'elixir', label: 'Elixir' },
  { id: 'erlang', label: 'Erlang' },
  { id: 'clojure', label: 'Clojure' },
  { id: 'fsharp', label: 'F#' },
  { id: 'fortran', label: 'Fortran' },
  { id: 'pascal', label: 'Pascal' },
  { id: 'vb', label: 'VB.NET' },
  { id: 'objective-c', label: 'Objective-C' },
  { id: 'julia', label: 'Julia' },
  { id: 'zig', label: 'Zig' },
  { id: 'nim', label: 'Nim' },
  { id: 'crystal', label: 'Crystal' },
  { id: 'assembly', label: 'Assembly' },
  { id: 'cobol', label: 'COBOL' },
  { id: 'lisp', label: 'Lisp' },
  { id: 'ocaml', label: 'OCaml' },
  { id: 'vlang', label: 'V' },
  { id: 'solidity', label: 'Solidity' },
  { id: 'react', label: 'React' },
  { id: 'vue', label: 'Vue' },
  { id: 'svelte', label: 'Svelte' },
  { id: 'mysql', label: 'MySQL' },
  { id: 'oracle', label: 'Oracle' },
  { id: 'postgresql', label: 'PostgreSQL' },
  { id: 'mongodb', label: 'MongoDB' },
  { id: 'sqlite', label: 'SQLite' },
  { id: 'redis', label: 'Redis' },
  { id: 'mariadb', label: 'MariaDB' },
  { id: 'plsql', label: 'PL/SQL' },
  { id: 'mssql', label: 'SQL Server' },
  { id: 'cassandra', label: 'Cassandra' },
  { id: 'questdb', label: 'QuestDB' },
  { id: 'duckdb', label: 'DuckDB' },
  { id: 'surrealdb', label: 'SurrealDB' },
  { id: 'firebird', label: 'Firebird' },
  { id: 'clickhouse', label: 'ClickHouse' },
  { id: 'angular', label: 'Angular' },
  { id: 'mui', label: 'MUI' },
  { id: 'chakra', label: 'Chakra UI' },
  { id: 'shadcn', label: 'shadcn' },
  { id: 'mantine', label: 'Mantine' },
  { id: 'htmx', label: 'HTMX' },
  { id: 'alpine', label: 'Alpine.js' },
  { id: 'mermaid', label: 'Mermaid' },
  { id: 'echarts', label: 'ECharts' },
  { id: 'leaflet', label: 'Leaflet' },
  { id: 'daisyui', label: 'daisyUI' },
  { id: 'phaser', label: 'Phaser' },
  { id: 'bulma', label: 'Bulma' },
  { id: 'foundation', label: 'Foundation' },
  { id: 'deno', label: 'Deno' },
  { id: 'bun', label: 'Bun' },
  { id: 'brainfuck', label: 'Brainfuck' },
  { id: 'coffeescript', label: 'CoffeeScript' },
  { id: 'ejs', label: 'EJS' },
  { id: 'matplotlib', label: 'Matplotlib' },
  { id: 'pygame', label: 'Pygame' },
  { id: 'seaborn', label: 'Seaborn' },
];

export const FALLBACK_PISTON_VERSION: Record<string, string> = {
  python: '3.12.0',
  java: '15.0.2',
  c: '10.2.0',
  'c++': '10.2.0',
  csharp: '6.12.0',
  go: '1.16.2',
  rust: '1.68.2',
  php: '8.2.3',
  ruby: '3.0.1',
  kotlin: '1.8.20',
  swift: '5.3.3',
  lua: '5.4.4',
  sqlite3: '3.36.0',
  javascript: '18.15.0',
  typescript: '5.0.3',
  bash: '5.2.0',
  perl: '5.36.0',
  r: '4.1.1',
  dart: '2.19.6',
  scala: '3.2.2',
  groovy: '3.0.7',
  haskell: '9.0.1',
  elixir: '1.11.3',
  erlang: '23.0.0',
  clojure: '1.10.3',
  fsharp: '5.0',
  fortran: '10.2.0',
  pascal: '3.2.2',
  'basic.net': '5.0.201',
  'objective-c': '10.2.0',
  julia: '1.8.5',
  zig: '0.10.1',
  nim: '1.6.12',
  crystal: '1.7.2',
  assembly: '2.14.02',
  nasm: '2.15.05',
  powershell: '7.1.4',
  coffeescript: '2.5.1',
  cobol: '3.1.2',
  lisp: '2.1.2',
  prolog: '8.2.4',
  ocaml: '4.12.0',
  vlang: '0.3.3',
  solidity: '0.8.19',
};


/** Full catalog for picker / landing (groups) */
export const LANG_CATALOG: Record<string, { id: string; label: string; mode: 'preview' | 'remote' | 'sql-demo' }[]> = {
  popular: [
    { id: 'html', label: 'HTML', mode: 'preview' },
    { id: 'python', label: 'Python', mode: 'remote' },
    { id: 'javascript', label: 'JavaScript', mode: 'remote' },
    { id: 'java', label: 'Java', mode: 'remote' },
    { id: 'mysql', label: 'MySQL', mode: 'sql-demo' },
    { id: 'c', label: 'C', mode: 'remote' },
    { id: 'cpp', label: 'C++', mode: 'remote' },
    { id: 'php', label: 'PHP', mode: 'remote' },
    { id: 'csharp', label: 'C#', mode: 'remote' },
    { id: 'nodejs', label: 'NodeJS', mode: 'remote' },
    { id: 'react', label: 'React', mode: 'preview' },
    { id: 'postgresql', label: 'PostgreSQL', mode: 'sql-demo' },
  ],
  programming: [
    { id: 'python', label: 'Python', mode: 'remote' },
    { id: 'java', label: 'Java', mode: 'remote' },
    { id: 'c', label: 'C', mode: 'remote' },
    { id: 'cpp', label: 'C++', mode: 'remote' },
    { id: 'javascript', label: 'JavaScript', mode: 'remote' },
    { id: 'typescript', label: 'TypeScript', mode: 'remote' },
    { id: 'go', label: 'Go', mode: 'remote' },
    { id: 'rust', label: 'Rust', mode: 'remote' },
    { id: 'php', label: 'PHP', mode: 'remote' },
    { id: 'ruby', label: 'Ruby', mode: 'remote' },
    { id: 'csharp', label: 'C#', mode: 'remote' },
    { id: 'kotlin', label: 'Kotlin', mode: 'remote' },
    { id: 'swift', label: 'Swift', mode: 'remote' },
    { id: 'lua', label: 'Lua', mode: 'remote' },
    { id: 'dart', label: 'Dart', mode: 'remote' },
    { id: 'scala', label: 'Scala', mode: 'remote' },
    { id: 'haskell', label: 'Haskell', mode: 'remote' },
    { id: 'r', label: 'R', mode: 'remote' },
    { id: 'julia', label: 'Julia', mode: 'remote' },
    { id: 'zig', label: 'Zig', mode: 'remote' },
    { id: 'nim', label: 'Nim', mode: 'remote' },
    { id: 'assembly', label: 'Assembly', mode: 'remote' },
    { id: 'bash', label: 'Bash', mode: 'remote' },
    { id: 'perl', label: 'Perl', mode: 'remote' },
  ],
  web: [
    { id: 'html', label: 'HTML', mode: 'preview' },
    { id: 'react', label: 'React', mode: 'preview' },
    { id: 'vue', label: 'Vue', mode: 'preview' },
    { id: 'angular', label: 'Angular', mode: 'preview' },
    { id: 'svelte', label: 'Svelte', mode: 'preview' },
    { id: 'tailwind', label: 'Tailwind CSS', mode: 'preview' },
    { id: 'bootstrap', label: 'Bootstrap', mode: 'preview' },
    { id: 'jquery', label: 'jQuery', mode: 'preview' },
    { id: 'threejs', label: 'Three.js', mode: 'preview' },
    { id: 'd3', label: 'D3.js', mode: 'preview' },
    { id: 'chartjs', label: 'Chart.js', mode: 'preview' },
  ],
  database: [
    { id: 'mysql', label: 'MySQL', mode: 'sql-demo' },
    { id: 'postgresql', label: 'PostgreSQL', mode: 'sql-demo' },
    { id: 'sqlite', label: 'SQLite', mode: 'sql-demo' },
    { id: 'mariadb', label: 'MariaDB', mode: 'sql-demo' },
    { id: 'oracle', label: 'Oracle', mode: 'sql-demo' },
    { id: 'mssql', label: 'SQL Server', mode: 'sql-demo' },
    { id: 'mongodb', label: 'MongoDB', mode: 'remote' },
    { id: 'redis', label: 'Redis', mode: 'remote' },
  ],
};

